name: workflow development branch

on:
  push:
    branches:
      - development
jobs:
  
  build-and-deploy-for development:
  
  runs-on: ubuntu-latest
  
  steps:
- name: from development branch
  run : | 
    echo "hello"

