name: workflow development branch

on:
  push:
    branches:
    - development

jobs:
  
  build-and-deploy-for-development:
  
    runs-on: ubuntu-latest
  
    steps:
      - name: from development branch
        run: echo "hello from first workflow"

  build-and-deploy-for-development-for-second:
  
    runs-on: ubuntu-latest
    needs: [build-and-deploy-for-development]
    steps:
      - name: from development branch
        
        uses: actions/checkout@v4

      - name: setup .net framework
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: build
        run: dotnet build

      - name: test dotnet
        run: dotnet test --no-build --verbosity normal

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: log into docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
